codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: yes


flags:
  admin:
    paths:
      - src/admin/**/*
    carryforward: false
  everything-else:
    ignore:
      - src/admin/**/*
    carryforward: false
